export type VocabKeypadQ = {
    id: string;
    sentence: string;   // 빈칸은 반드시 "()" 토큰
    answers: string[];  // 빈칸 개수와 동일
    explain?: string;
  };
  
  export const VOCAB_GAME_ITEMS: VocabKeypadQ[] = [

        {
          id: "q1",
          sentence: "Hello! () Somin.",
          answers: ["Iam"],
          explain: "안녕! 나는 소민이야.",
        },
        {
          id: "q2",
          sentence: "I'm 15 () old, and I live in Korea",
          answers: ["years"],
          explain: "나는 15살이고 한국에 살아.",
        },
        {
          id: "q3",
          sentence: "I'm 15 years old, and I () Korea",
          answers: ["livein"],
          explain: "나는 15살이고 한국에 살아.",
        },
        {
          id: "q4",
          sentence: "Please tell me () your favorite time of the day.",
          answers: ["about"],
          explain: "너희들이 하루 중 가장 좋아하는 시간에 대해 내게 말해 줘.",
        },
        {
          id: "q5",
          sentence: "Please tell me about your favorite time () the day.",
          answers: ["of"],
          explain: "너희들이 하루 중 가장 좋아하는 시간에 대해 내게 말해 줘.",
        },
        {
          id: "q6",
          sentence: "My favorite time of the day is () the afternoon.",
          answers: ["in"],
          explain: "하루 중 내가 가장 좋아하는 시간은 오후이다.",
        },
        {
          id: "q7",
          sentence: "I'm usually () school at two o'clock.",
          answers: ["outof"],
          explain: "나는 보통 두 시에 학교를 끝낸다.",
        },
        {
          id: "q8",
          sentence: "I then come back () my house.",
          answers: ["to"],
          explain: "나는 그 후 집으로 돌아온다.",
        },
        {
          id: "q9",
          sentence: "My mom is already () home.",
          answers: ["at"],
          explain: "엄마는 이미 집에 계신다.",
        },
        {
          id: "q10",
          sentence: "She () me with a smile.",
          answers: ["greets"],
          explain: "엄마는 미소로 나를 맞이하신다.",
        },
        {
          id: "q11",
          sentence: "Then I take a () in my room.",
          answers: ["rest"],
          explain: "그 다음 나는 방에서 휴식을 취한다.",
        },
        {
          id: "q12",
          sentence: "A little later, I listen () music.",
          answers: ["to"],
          explain: "조금 뒤에 나는 음악을 듣는다.",
        },
        {
          id: "q13",
          sentence: "I often talk to my best friend () the phone, too.",
          answers: ["on"],
          explain: "또 나는 전화로 가장 친한 친구와 자주 이야기한다.",
        },
        {
          id: "q14",
          sentence: "We talk about our day () make each other laugh.",
          answers: ["and"],
          explain: "우리는 하루에 대해 이야기하고 서로 웃게 만든다.",
        },
        {
          id: "q15",
          sentence: "After that, I do my homework () my desk.",
          answers: ["at"],
          explain: "그 후 나는 책상에서 숙제를 한다.",
        },
        {
          id: "q16",
          sentence: "I finish it () and go outside.",
          answers: ["early"],
          explain: "나는 그것을 일찍 끝내고 밖으로 나간다.",
        },
        {
          id: "q17",
          sentence: "I meet my friends at the () near my house.",
          answers: ["park"],
          explain: "나는 집 근처 공원에서 친구들을 만난다.",
        },
        {
          id: "q18",
          sentence: "We play soccer or ride our () together.",
          answers: ["bikes"],
          explain: "우리는 함께 축구를 하거나 자전거를 탄다.",
        },
        {
          id: "q19",
          sentence: "Sometimes we just () and talk.",
          answers: ["walk"],
          explain: "가끔 우리는 그냥 걸으며 이야기한다.",
        },
        {
          id: "q20",
          sentence: "We have a great time () the evening.",
          answers: ["in"],
          explain: "우리는 저녁에 즐거운 시간을 보낸다.",
        },
        {
          id: "q21",
          sentence: "At six, I go back home and take a ().",
          answers: ["shower"],
          explain: "여섯 시에 나는 집에 돌아와 샤워를 한다.",
        },
        {
          id: "q22",
          sentence: "Then I help my mom () dinner.",
          answers: ["make"],
          explain: "그 다음 나는 엄마의 저녁 준비를 돕는다.",
        },
        {
          id: "q23",
          sentence: "We eat dinner () seven.",
          answers: ["at"],
          explain: "우리는 일곱 시에 저녁을 먹는다.",
        },
        {
          id: "q24",
          sentence: "After dinner, we watch TV () a while.",
          answers: ["for"],
          explain: "저녁 후 우리는 잠시 TV를 본다.",
        },
        {
          id: "q25",
          sentence: "My dad usually () funny shows.",
          answers: ["chooses"],
          explain: "아빠는 보통 재미있는 프로그램을 고른다.",
        },
        {
          id: "q26",
          sentence: "We laugh a lot and () relaxed.",
          answers: ["feel"],
          explain: "우리는 많이 웃고 편안함을 느낀다.",
        },
        {
          id: "q27",
          sentence: "At nine, I get ready () bed.",
          answers: ["for"],
          explain: "아홉 시에 나는 잠잘 준비를 한다.",
        },
        {
          id: "q28",
          sentence: "I brush my teeth and wash my () .",
          answers: ["face"],
          explain: "나는 이를 닦고 얼굴을 씻는다.",
        },
        {
          id: "q29",
          sentence: "Then I read a book () my bed.",
          answers: ["in"],
          explain: "그 다음 나는 침대에서 책을 읽는다.",
        },
        {
          id: "q30",
          sentence: "Reading helps me () down.",
          answers: ["calm"],
          explain: "독서는 나를 진정시키는 데 도움이 된다.",
        },
        {
          id: "q31",
          sentence: "I usually fall asleep () ten.",
          answers: ["at"],
          explain: "나는 보통 열 시에 잠든다.",
        },
        {
          id: "q32",
          sentence: "I think my routine is simple but ().",
          answers: ["happy"],
          explain: "내 일과는 단순하지만 행복하다고 생각한다.",
        },
        {
          id: "q33",
          sentence: "It's important to have a good () every day.",
          answers: ["habit"],
          explain: "매일 좋은 습관을 가지는 것은 중요하다.",
        },
        {
          id: "q34",
          sentence: "I try to use my time () .",
          answers: ["well"],
          explain: "나는 시간을 잘 쓰려고 노력한다.",
        },
        {
          id: "q35",
          sentence: "How about you? What's your favorite time of the day () ?",
          answers: ["too"],
          explain: "너는 어때? 너도 하루 중 가장 좋아하는 시간이 뭐야?",
        },
        {
          id: "q36",
          sentence: "Do you have a routine like () ?",
          answers: ["mine"],
          explain: "너도 나처럼 일과가 있니?",
        },
        {
          id: "q37",
          sentence: "I hope you can enjoy your day and stay ().",
          answers: ["healthy"],
          explain: "너도 하루를 즐기고 건강하게 지내길 바란다.",
        },
        {
          id: "q38",
          sentence: "Thank you for reading my () .",
          answers: ["story"],
          explain: "내 이야기를 읽어줘서 고마워.",
        },
        {
          id: "q39",
          sentence: "I want to hear about your day () .",
          answers: ["soon"],
          explain: "곧 네 하루 이야기도 듣고 싶어.",
        },
        {
          id: "q40",
          sentence: "Let's be friends and keep in () .",
          answers: ["touch"],
          explain: "친구가 되어서 계속 연락하자.",
        },
        {
          id: "q41",
          sentence: "Have a nice day and see you () time!",
          answers: ["next"],
          explain: "좋은 하루 보내고 다음에 보자!",
        },
        {
          id: "q42",
          sentence: "My sister is in the () grade.",
          answers: ["sixth"],
          explain: "내 여동생은 6학년이야.",
        },
        {
          id: "q43",
          sentence: "She likes () cartoons.",
          answers: ["watching"],
          explain: "그녀는 만화를 보는 걸 좋아해.",
        },
        {
          id: "q44",
          sentence: "She wants to be an () artist.",
          answers: ["animation"],
          explain: "그녀는 애니메이션 작가가 되고 싶어해.",
        },
        {
          id: "q45",
          sentence: "She draws pictures every () .",
          answers: ["day"],
          explain: "그녀는 매일 그림을 그려.",
        },
        {
          id: "q46",
          sentence: "I think she will be very () someday.",
          answers: ["famous"],
          explain: "나는 언젠가 그녀가 매우 유명해질 거라 생각해.",
        },
        {
          id: "q47",
          sentence: "I want to () like them.",
          answers: ["be"],
          explain: "나도 그들처럼 되고 싶어.",
        },
        {
          id: "q48",
          sentence: "Take () of yourself.",
          answers: ["care"],
          explain: "몸조심해.",
        },
        {
          id: "q49",
          sentence: "See you () time.",
          answers: ["next"],
          explain: "다음에 보자.",
        },
        {
          id: "q50",
          sentence: "My favorite subject is () .",
          answers: ["english"],
          explain: "내가 가장 좋아하는 과목은 영어야.",
        },
        {
          id: "q51",
          sentence: "I like () books.",
          answers: ["reading"],
          explain: "나는 책 읽는 것을 좋아해.",
        },
        {
          id: "q52",
          sentence: "I usually read books after () .",
          answers: ["school"],
          explain: "나는 보통 방과 후에 책을 읽어.",
        },
        {
          id: "q53",
          sentence: "My hobby is playing the () .",
          answers: ["piano"],
          explain: "내 취미는 피아노 치는 거야.",
        },
      ] as const;
      